# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-09-01 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mapQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(default='', max_length=255)),
                ('label', models.CharField(default='', max_length=255)),
                ('num', models.IntegerField()),
                ('aboveNum', models.IntegerField()),
                ('belowNum', models.IntegerField()),
                ('num0', models.IntegerField()),
                ('aboveNum0', models.IntegerField()),
                ('belowNum0', models.IntegerField()),
                ('num1', models.IntegerField()),
                ('aboveNum1', models.IntegerField()),
                ('belowNum1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('aboveNum2', models.IntegerField()),
                ('belowNum2', models.IntegerField()),
                ('num3', models.IntegerField()),
                ('aboveNum3', models.IntegerField()),
                ('belowNum3', models.IntegerField()),
                ('num4', models.IntegerField()),
                ('aboveNum4', models.IntegerField()),
                ('belowNum4', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='mapquery',
            unique_together=set([('area', 'label')]),
        ),
    ]
