# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-09-01 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20220901_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapquery',
            name='cities',
            field=models.CharField(default='', max_length=255),
        ),
    ]
