# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-09-01 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_mapquery_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='stkcdInCity',
            fields=[
                ('city', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stkcd', models.CharField(max_length=2805)),
            ],
        ),
    ]
