# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-09-09 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_stkcdincity'),
    ]

    operations = [
        migrations.CreateModel(
            name='predictModelPath',
            fields=[
                ('id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('stkcd', models.CharField(max_length=255)),
                ('begindate', models.CharField(max_length=255)),
                ('enddate', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='predictmodelpath',
            unique_together=set([('stkcd', 'begindate', 'enddate')]),
        ),
    ]
