# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-09-13 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20220909_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='regQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(default='', max_length=255)),
                ('label', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
                ('weather', models.CharField(default='', max_length=255)),
                ('cities', models.CharField(default='', max_length=510)),
                ('weights', models.FloatField()),
                ('score', models.FloatField()),
                ('num', models.IntegerField()),
            ],
        ),
    ]
