# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-11-03 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_map_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='weather',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
