# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2022-11-08 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20221103_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='stkPlace',
            fields=[
                ('stkcd', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name1', models.CharField(max_length=255)),
                ('name2', models.CharField(max_length=255)),
                ('place1', models.CharField(max_length=255)),
                ('place2', models.CharField(max_length=255)),
            ],
        ),
    ]
