# Generated by Django 3.2 on 2022-12-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_stkplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='stkBacktestResult',
            fields=[
                ('stkcd', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=255)),
                ('date', models.TextField()),
                ('asset', models.TextField()),
                ('price', models.TextField()),
                ('inDate', models.CharField(max_length=2550)),
                ('outDate', models.CharField(max_length=2550)),
            ],
        ),
    ]
